New giveaways
Craftserve/CraftserveDiscordBot pull request #1
Opened 2024-05-13 09:34 UTC by TheTuso

2024-05-13 13:15 UTC, Rekseto requested changes

2024-05-13 13:15 UTC, Rekseto commented on cmd/bot/main.go
> +		log.Warn("!!! Running in developer mode !!!")
Dont use that many !!!

2024-05-19 17:50 UTC, Rekseto requested changes

2024-05-19 17:50 UTC, Rekseto commented on commands/CsrvbotCommand.go
> +	case "unconditionalgiveawaychannel":
could an an enum somewhere in code?

2024-05-19 17:50 UTC, Rekseto commented on commands/CsrvbotCommand.go
> +		discord.RespondWithMessage(ctx, s, i, "Nie udało się ustawić kanału")
it would be nice to add sentry trail (should be fairly easy, we can modify a bit logger to have sentry middleware)

2024-05-19 17:50 UTC, Rekseto commented on pkg/discord/embeds.go
> +			URL:     "https://craftserve.pl",
config value?

2024-05-20 09:51 UTC, TheTuso commented on pkg/discord/embeds.go
> +			URL:     "https://craftserve.pl",
Done

2024-05-20 10:05 UTC, TheTuso commented on commands/CsrvbotCommand.go
> +	case "unconditionalgiveawaychannel":
Done

2024-05-23 18:33 UTC, TheTuso commented on commands/CsrvbotCommand.go
> +		discord.RespondWithMessage(ctx, s, i, "Nie udało się ustawić kanału")
Done

2024-05-27 10:17 UTC, Rekseto requested changes

2024-05-27 10:17 UTC, Rekseto commented on cmd/bot/main.go
> +		log.Errorf("Could not set unconditional giveaway cron job: %v", err)
could be Fatalf

2024-05-27 10:17 UTC, Rekseto commented on cmd/bot/main.go
> +		log.Errorf("Could not set conditional giveaway cron job: %v", err)
Could be Fatalf

2024-05-27 10:17 UTC, Rekseto commented on default_config.json
>      "host": "address:port",
create directory resources and put configuration.sample.json there instead of deafult_config.json

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +package repos
There is no difference between conditional giveway and unconditional giveaway except Level int so just create one table with NULLABLE ;) null == unconditional giveaway, != null conditional giveaway. That way you have fewer tables and structs

2024-05-27 10:17 UTC, Rekseto commented on internal/services/csrvclient.go
>  	req, err := http.NewRequest("POST", "https://craftserve.pl/api/generate_voucher", nil)
http.PostMethod, create url as variable above (pass url from config here also)

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +func (repo *ConditionalGiveawayRepo) GetGiveawayForGuild(ctx context.Context, guildId string) (ConditionalGiveaway, error) {
internal repo struct types never should escape repo

2024-05-27 10:17 UTC, Rekseto commented on commands/CsrvbotCommand.go
> -func NewCsrvbotCommand(giveawayHours string, serverRepo *repos.ServerRepo, giveawayRepo *repos.GiveawayRepo, userRepo *repos.UserRepo, csrvClient *services.CsrvClient, giveawayService *services.Givea
interface of repositories should be used instead

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +func (repo *ConditionalGiveawayRepo) UpdateGiveaway(ctx context.Context, giveaway *ConditionalGiveaway, messageId string) error {
its named wrongly, it should End/Finish Giveaway (Update means just updating all / majority of fields)

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +	result, err := repo.mysql.WithContext(ctx).SelectInt("SELECT COUNT(*) FROM conditional_giveaways, conditional_giveaway_winners WHERE info_message_id = ? AND user_id = ? AND conditional_giveaways.id
use JOIN instead

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +	code, err := repo.mysql.WithContext(ctx).SelectStr("SELECT code FROM conditional_giveaways, conditional_giveaway_winners WHERE info_message_id = ? AND user_id = ? AND conditional_giveaways.id = cond
use JOIN instead

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +	code, err := repo.mysql.WithContext(ctx).SelectStr("SELECT code FROM conditional_giveaways, conditional_giveaway_winners WHERE info_message_id = ? AND user_id = ? AND conditional_giveaways.id = cond
also just create method GetGiveawayByMessageId

2024-05-27 10:17 UTC, Rekseto commented on internal/repos/mysql_conditional_giveaway_repo.go
> +func (repo *ConditionalGiveawayRepo) IsGiveawayFinishedByMessageId(ctx context.Context, messageId string) (bool, error) {
useless if GetGiveawayByMessageId would exist

2024-05-27 10:17 UTC, Rekseto commented on internal/services/giveawayservice.go
>  )
will be simpler if there would be no difference between unconditional and conditional giveaways

2024-05-27 10:17 UTC, Rekseto commented on listeners/InteractionCreateListener.go
> +	case "unconditionalgiveawayjoin":
giveaway_join and then just add if giveway.Levels != nil {} and handle your logic based on that

2024-06-03 12:07 UTC, Rekseto requested changes

2024-06-03 12:07 UTC, Rekseto commented on internal/repos/mysql_message_giveaway_repo.go
could be giveaway repo

2024-06-03 12:07 UTC, Rekseto commented on internal/repos/mysql_joinable_giveaway_repo.go
> +package repos
joinable giveaway and giveaway why the difference?

2024-06-26 11:28 UTC, merged